### PR TITLE
fix language indexing.

### LINKED ISSUE #565: fix language indexing
### Background

There is a desire to keep certain DOR/Argo Solr index fields as similar to SearchWorks indexing as possible.  This was previously handled by using the same code in the `stanford-mods` gem for both this app and for SearchWorks to get the values for Solr fields.

PR #517 decoupled dor indexing from Fedora (MODS), but was done without this realization, so the algorithms for retrieving values for Solr from our (Cocina) descriptive metadata were inadvertently over-simplified.  Also, the original tests for the dor_indexing_app were not at all thorough in exploring different data conditions and how they would be indexed.

### What Needs to be Done

This ticket is to make the `sw_language_ssim` field contain values as much like the ones we were getting from the stanford-mods method as is reasonable.

Per PR #517, `sw_language_ssim` Solr field was formerly populated by calling `sw_language_facet` in stanford-mods (https://github.com/sul-dlss/stanford-mods/blob/master/lib/stanford-mods/searchworks.rb#L24).  Tracing through the logic,  you see it looks for language codes (in our case, ask Arcadia which authority values for lang codes) and has a hash to look up the codes https://github.com/sul-dlss/stanford-mods/blob/master/lib/stanford-mods/searchworks_languages.rb.  We could include the gem for this hash lookup, or perhaps Arcadia would like us to use the actual authority text value (which is truthfully where that hash was populated from originally).  Note that it also uses text values as the Solr field allows for multiple values.

- Work with Arcadia to find the corresponding information ^^ in cocina models.
    - ask her what to do if there are mulitple authorities or codes and text values, multiple scripts, etc. in Cocina
- Write tests that exercise the different use cases
- ensure you account for the possibility of more complex data in the relevant cocina models by referring to the appropriate mapping specs in the dor-services-app, e.g. https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/language_spec.rb.    That is, if the code only expects "language.value" it won't find any values inside a script block, etc. and all that sort of stuff.

### User Impact
We are likely not populating the language Solr fields for some use cases (e.g. when the data has a script) and we are likely giving Argo users a mistaken impression of how their data will appear in SearchWorks.

Note that in a perfect world, we will want to reindex all data that was indexed after PR #517 was deployed.

### Completion

Part of completing this issue is addressing all of the `xit` specs in spec/indexers/descriptive_metadata/language_spec.rb

### PR DESCRIPTION
**Pull request by justinlittman**
closes #565

## Why was this change made?
Implement Arcadia's mapping for languages.

## How was this change tested?
Unit

## Which documentation and/or configurations were updated?
NA

### CODE REVIEW

File: app/services/language_builder.rb [hunk 1]
```diff
@@ -5,17 +5,50 @@ class LanguageBuilder
...
+    end.uniq.compact.presence
+  end
+
+  private
+
+  attr_reader :languages
+
+  # rubocop:disable Metrics/CyclomaticComplexity
+  # rubocop:disable Metrics/PerceivedComplexity
+  def iso_639?(lang)
```
Comment (jcoyne) [inline app/services/language_builder.rb:33]: 😱

**Review by jcoyne — APPROVED** [review]

File: app/services/language_builder.rb (hunk 1 above)
Comment (justinlittman) [reply app/services/language_builder.rb:33]: And this is "normalized" data ...
