### PR TITLE
More flexible mapping of marcgac and marc countries.

### LINKED ISSUE #633: [dor_indexing_app/prod] KeyError: key not found: "e-ru---"
Did you mean?  "e-ru"
## Backtrace

    line 54 of [PROJECT_ROOT]/app/services/geographic_builder.rb: place_from_code
    line 41 of [PROJECT_ROOT]/app/services/geographic_builder.rb: build_place
    line 34 of [PROJECT_ROOT]/app/services/geographic_builder.rb: block in build_place_nodes

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49898/faults/79112258)

### PR DESCRIPTION
**Pull request by justinlittman**
closes #633

## Why was this change made?
* Handle marcgac that include trailing spaces.
* Don't error when marcgac or country code not found.

## How was this change tested?
Unit

## Which documentation and/or configurations were updated?
NA

### CODE REVIEW

File: app/services/geographic_builder.rb [hunk 1]
```diff
@@ -48,12 +48,13 @@ def build_place(node)
   def place_from_code(node)
     return [] unless node.code && node.source
 
-    code = node.code.sub(/[^\w-]/, '') # remove any punctuation (except dash).
+    code_with_dashes = node.code.gsub(/[^\w-]/, '') # remove any punctuation (except dash).
+    code_without_dashes = code_with_dashes.sub(/-+$/, '') # remove trailing dashes.
     case node.source.code
     when 'marcgac'
-      [Marc::Vocab::GeographicArea.fetch(code)]
+      [Marc::Vocab::GeographicArea::TERMS[code_with_dashes] || Marc::Vocab::GeographicArea::TERMS[code_without_dashes]].compact
```
Comment (jcoyne) [inline app/services/geographic_builder.rb:55]: Please use `fetch` with a default (`nil`) here rather than addressing the constants (which is an implementation detail).

File: app/services/geographic_builder.rb [hunk 2]
```diff
@@ -48,12 +48,13 @@ def build_place(node)
   def place_from_code(node)
     return [] unless node.code && node.source
 
-    code = node.code.sub(/[^\w-]/, '') # remove any punctuation (except dash).
+    code_with_dashes = node.code.gsub(/[^\w-]/, '') # remove any punctuation (except dash).
```
Comment (jcoyne) [inline app/services/geographic_builder.rb:51]: Should this be in DSA?  Shouldn't the cocina model only have valid codes?

File: app/services/geographic_builder.rb [hunk 3]
```diff
@@ -48,12 +48,13 @@ def build_place(node)
...
+    code_without_dashes = code_with_dashes.sub(/-+$/, '') # remove trailing dashes.
```
Comment (jcoyne) [inline app/services/geographic_builder.rb:52]: Should this be in DSA? Shouldn't the cocina model only have valid codes?

File: app/services/geographic_builder.rb (hunk 1 above)
Comment (justinlittman) [reply app/services/geographic_builder.rb:55]: Duh.

Comment (justinlittman) [reply app/services/geographic_builder.rb:55]: Oh wait, it doesn't take a default.

File: app/services/geographic_builder.rb (hunk 3 above)
Comment (justinlittman) [reply app/services/geographic_builder.rb:52]: Depends on how you define "valid" I guess ...

I'm not opposed to a separate ticket in dor-services-app to consider.

File: app/services/geographic_builder.rb (hunk 1 above)
Comment (jcoyne) [reply app/services/geographic_builder.rb:55]: `bundle update marc-vocab`

File: app/services/geographic_builder.rb (hunk 3 above)
Comment (jcoyne) [reply app/services/geographic_builder.rb:52]: I would expect that valid means any marcgac codes to be on the list that LOC publishes.

File: app/services/geographic_builder.rb (hunk 1 above)
Comment (jcoyne) [reply app/services/geographic_builder.rb:55]: The 0.3.0 version does.

File: app/services/geographic_builder.rb (hunk 3 above)
Comment (justinlittman) [reply app/services/geographic_builder.rb:52]: https://github.com/sul-dlss/dor-services-app/issues/2805

**Review by jcoyne — APPROVED** [review]
