### PR TITLE
fix pub date indexing

### LINKED ISSUE #554: Fix indexing of publication dates
**Describe the bug**
See sul-dlss/infrastructure-integration-test/issues/219 -- at a minimum, we are not correctly indexing publication dates we receive from Hydrus.

The algorithm from @arcadiafalcone for publication date to index is:
1. event with date with type publication and status primary; 
2. event with date with type publication and event has event type publication; 
3. event with date with type publication (again assuming that you're looking to return a single date or range)

There is a WIP PR up:  #553  using `event-date` branch

**User Impact**
- objects coming from Hydrus are not appearing in Argo correctly because their publication date is not getting into Solr properly.

**To Reproduce**
run `deposit_via_hydrus_spec` infrastructure-integration test and note that it fails on line 81.

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

Fixes #554, which is hoped to also fix sul-dlss/infrastructure-integration-test/issues/219

Part of #571;  this still doesn't address sul-dlss/infrastructure-integration-test/issues/219.

index pub dates properly.

### CODE REVIEW

File: app/indexers/describable_indexer.rb [hunk 1]
```diff
@@ -109,17 +107,39 @@ def archived_website?
...
+  def periodical?
+    event_selector('publication')&.note&.any? { |note| note.type == 'issuance' && note.value == 'serial' }
+  end
+
+  def pub_date
+    pub_date = PubDateBuilder.build(event_selector('publication'), 'publication')
+    return pub_date if pub_date.present?
+
+    pub_date = PubDateBuilder.build(event_selector('creation'), 'creation')
+    return pub_date if pub_date.present?
```
Comment (jcoyne) [inline app/indexers/describable_indexer.rb:122]: is this check necessary?   can this method be 

```ruby
PubDateBuilder.build(event_selector('publication'), 'publication') ||
  PubDateBuilder.build(event_selector('creation'), 'creation') ||
```

Is pubDateBuilder returning empty strings?

File: app/indexers/describable_indexer.rb [hunk 2]
```diff
@@ -109,17 +107,39 @@ def archived_website?
     genres.include?('archived website')
   end
 
+  # TODO: part of https://github.com/sul-dlss/dor_indexing_app/issues/567
+  # From Arcadia, it should be:
+  #  typeOfResource is "text" and any of: issuance is "continuing", issuance is "serial", frequency has a value
+  def periodical?
+    event_selector('publication')&.note&.any? { |note| note.type == 'issuance' && note.value == 'serial' }
```
Comment (jcoyne) [inline app/indexers/describable_indexer.rb:114]: Is there a reason this method got moved up from where it was previously?

File: app/indexers/describable_indexer.rb [hunk 3]
```diff
@@ -109,17 +107,39 @@ def archived_website?
...
+
+  def pub_date
+    pub_date = PubDateBuilder.build(event_selector('publication'), 'publication')
+    return pub_date if pub_date.present?
+
+    pub_date = PubDateBuilder.build(event_selector('creation'), 'creation')
+    return pub_date if pub_date.present?
+  end
+
+  def sw_format_for_text
```
Comment (jcoyne) [inline app/indexers/describable_indexer.rb:125]: Is there a reason this method got moved from it's previous position?

File: app/services/pub_date_builder.rb [hunk 4]
```diff
@@ -26,9 +26,9 @@ def self.pub_date_from_status_primary(event_dates)
   private_class_method :pub_date_from_status_primary
 
   # @return String date.value from a date of type of publication
```
Comment (jcoyne) [inline app/services/pub_date_builder.rb:28]: Would you mind fixing this yard doc?  I believe it can also return `NilClass`, too, right?

File: app/indexers/describable_indexer.rb (hunk 2 above)
Comment (ndushay) [reply app/indexers/describable_indexer.rb:114]: I moved what was a short "publication_event" method to the bottom since it became a long event_selector method.

File: app/indexers/describable_indexer.rb (hunk 1 above)
Comment (ndushay) [reply app/indexers/describable_indexer.rb:122]: feel free to change it - it's a production bug, and I'm out for 2nd jab ... and whatever reaction I get to it.

File: app/indexers/describable_indexer.rb (hunk 3 above)
Comment (ndushay) [reply app/indexers/describable_indexer.rb:125]: I moved what was a short "publication_event" method to the bottom since it became a long event_selector method.

File: app/services/pub_date_builder.rb (hunk 4 above)
Comment (ndushay) [reply app/services/pub_date_builder.rb:28]: feel free to change it.  We did work on this PR together in the beginning.

**Comment by ndushay** [comment]
sigh.  this now gets a pub date in Solr for a hydrus object, but, it still doesn't display in argo:

image

File: app/indexers/describable_indexer.rb (hunk 1 above)
Comment (ndushay) [reply app/indexers/describable_indexer.rb]: took your excellent suggestion

File: app/services/pub_date_builder.rb (hunk 4 above)
Comment (ndushay) [reply app/services/pub_date_builder.rb]: fixed.

**Comment by ndushay** [comment]
@jcoyne ready for your re-review.  It would be nice to get this in;  there is an open ticket to "finish" implementing the previous logic from stanford-mods, so this code will be revisited.

**Review by mjgiarlo — APPROVED** [review]
