### PR TITLE
Ensure that errors in finding collections don't result in further errors

### LINKED ISSUE #766: [dor_indexing_app/prod] NoMethodError: undefined method `description' for "16ae4ff7-9449-43af-9988-77772858878c":String
## Backtrace

    line 17 of [PROJECT_ROOT]/app/indexers/collection_title_indexer.rb: block (2 levels) in to_solr
    line 16 of [PROJECT_ROOT]/app/indexers/collection_title_indexer.rb: each
    line 16 of [PROJECT_ROOT]/app/indexers/collection_title_indexer.rb: block in to_solr

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49898/faults/83964667)

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made? 🤔
Fixes #766

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

### CODE REVIEW

**Review by jmartin-sul — APPROVED** [review]

**Review by jmartin-sul — APPROVED** [review]
approve pending lint fixup

File: spec/services/document_builder_spec.rb [hunk 1]
```diff
@@ -93,8 +93,15 @@
       end
 
       it 'logs to honeybadger' do
-        allow(Honeybadger).to receive(:notify)
+        allow(Honeybadger).to receive(:notify).and_return("16ae4ff7-9449-43af-9988-77772858878c")
```
Comment (jmartin-sul) [inline spec/services/document_builder_spec.rb:96]: rubocop was complaining about the double quote instead of single quote here
