### PR TITLE
fix title indexing

### LINKED ISSUE #563: fix title indexing (spec'ed but not done)
### Background

There is a desire to keep certain DOR/Argo Solr index fields as similar to SearchWorks indexing as possible.  This was previously handled by using the same code in the `stanford-mods` gem for both this app and for SearchWorks to get the values for Solr fields.

PR #517 decoupled dor indexing from Fedora (MODS), but was done without this realization, so the algorithms for retrieving values for Solr from our (Cocina) descriptive metadata were inadvertently over-simplified.  Also, the original tests for the dor_indexing_app were not at all thorough in exploring different data conditions and how they would be indexed.

### What Needs to be Done

This ticket is to make the `sw_display_title_tesim` field contain values as much like the ones we were getting from the stanford-mods method as is reasonable.

Per PR #517, `sw_display_title_tesim` Solr field was formerly populated by calling `sw_title_display` in stanford-mods (https://github.com/sul-dlss/stanford-mods/blob/master/lib/stanford-mods/searchworks.rb#L193).  Tracing through the logic, you see something like this:

`sw_title_display` gets a value from `sw_full_title` and then removes specific trailing punctuation
`sw_full_title` gets a value from non-sorting title chars, then title, then " : " then subTitle and then does stuff with partName and partNumber if present ... and then does some stuff with trailing punctuation.

- Work with Arcadia to find the corresponding information ^^ in cocina models.
    - ask her what to do if there are mulitple title values in Cocina
- Write tests that exercise different use cases
- ensure you account for the possibility of parallel data (e.g. multilingual) and structured data in the relevant cocina models by referring to the appropriate mapping specs in the dor-services-app, e.g. https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb.    That is, if the code only expects "title.value" it won't finded any structuredValues or parallelValues, and all that good stuff.

### User Impact
We are likely not populating the title field for some use cases (e.g. when the data is multi-lingual, or when it is structured) and we are likely giving Argo users a mistaken impression of how their data will appear in SearchWorks.

Note that in a perfect world, we will want to reindex all data that was indexed after PR #517 was deployed.

### PR DESCRIPTION
**Pull request by ndushay**
## Why was this change made?

Fixes #563

Fixes indexing for `sw_display_title_tesim` Solr field per Arcadia's specs

## How was this change tested?

unit tests; additionally ran some integration tests after deploying to qa

### CODE REVIEW

File: app/services/title_builder.rb [hunk 1]
```diff
@@ -4,38 +4,130 @@ class TitleBuilder
   # @param [Array<Cocina::Models::Title>] titles
   # @returns [String] the title value for Solr
   def self.build(titles)
-    title = titles.first
+    title = primary_title(titles) || first_untyped_title(titles) || titles.first
     if title.value
```
Comment (jcoyne) [inline app/services/title_builder.rb:8]: Can you pull the variable assignment out of the conditional, e.g:
```ruby
my_title = if title.value
  title.value
elsif title.structuredValue
  title_from_structured_values(...)
else
...
end
```

File: app/services/title_builder.rb [hunk 2]
```diff
@@ -4,38 +4,130 @@ class TitleBuilder
...
+  #   respect order of occurrence
+  #   separated from each other by comma space
+  # rubocop:disable Metrics/PerceivedComplexity
+  def self.title_from_structured_part(structured_values)
+    title_from_part = ''
+    structured_values.each do |structured_value|
+      case structured_value.type&.downcase
+      when 'part name', 'part number'
+        title_from_part = if title_from_part&.strip.present?
+                            "#{title_from_part.sub(/[ .,]*$/, '')}, #{structured_value.value&.strip}"
```
Comment (jcoyne) [inline app/services/title_builder.rb:124]: why is `value&.strip` used here? Are you expecting it to be nil?

File: app/services/title_builder.rb [hunk 3]
```diff
@@ -4,38 +4,130 @@ class TitleBuilder
...
+  # combine part name and part number:
+  #   respect order of occurrence
+  #   separated from each other by comma space
+  # rubocop:disable Metrics/PerceivedComplexity
+  def self.title_from_structured_part(structured_values)
+    title_from_part = ''
+    structured_values.each do |structured_value|
+      case structured_value.type&.downcase
+      when 'part name', 'part number'
+        title_from_part = if title_from_part&.strip.present?
```
Comment (jcoyne) [inline app/services/title_builder.rb:123]: title_from_part can never be nil here, so why use the `&.`?

File: app/services/title_builder.rb [hunk 4]
```diff
@@ -4,38 +4,130 @@ class TitleBuilder
...
+    end
+  end
+  private_class_method :primary_title
+
+  # @param [Array<Cocina::Models::Title>] titles
+  # @return [Cocina::Models::Title, nil] first title that has no type attribute
+  def self.first_untyped_title(titles)
+    titles.find do |title|
+      if title.parallelValue.present?
+        title.parallelValue&.find { |parallel_value| parallel_value.type.nil? }
```
Comment (jcoyne) [inline app/services/title_builder.rb:98]: you just checked that parallel value was present, so why use `parallelValue&.find`?

File: app/services/title_builder.rb [hunk 5]
```diff
@@ -4,38 +4,130 @@ class TitleBuilder
...
+    structured_values.each do |structured_value|
+      # There can be a structuredValue inside a structuredValue.  For example,
+      #   a uniform title where both the name and the title have internal StructuredValue
+      return title_from_structured_values(structured_value.structuredValue, non_sorting_char_count) if structured_value.structuredValue
+
+      value = structured_value.value&.strip
+      next unless value
+
+      # additional types:  name, uniform ...
+      case structured_value.type&.downcase
```
Comment (jcoyne) [inline app/services/title_builder.rb:34]: the `type&.downcase` implies that this might be `nil`, but there is no when or else case for that value. Is that something we need to deal with?

File: app/services/title_builder.rb [hunk 6]
```diff
@@ -4,38 +4,130 @@ class TitleBuilder
...
-      if title.structuredValue
-        [build_structured(title.structuredValue), '']
+  # rubocop:disable Metrics/BlockLength
+  # rubocop:disable Metrics/CyclomaticComplexity
+  # rubocop:disable Metrics/MethodLength
+  # rubocop:disable Metrics/PerceivedComplexity
+  def self.title_from_structured_values(structured_values, non_sorting_char_count)
+    structured_title = ''
+    title_from_part = ''
+    structured_values.each do |structured_value|
```
Comment (jcoyne) [inline app/services/title_builder.rb:25]: This appears to overwrite `structured_title` every time through this loop and then the method returns whatever one was set last?  Is that right?

Comment (ndushay) [reply app/services/title_builder.rb:25]: there is only one ultimate value for each structuredValue -- it is the amalgamation of all the diff pieces.

File: app/services/title_builder.rb (hunk 5 above)
Comment (ndushay) [reply app/services/title_builder.rb:34]: I don't know;  Arcadia didn't have an example for it.  I asked her what other types will show up here and she is looking into it.  No reason to hold up this PR for those edge cases.

File: app/services/title_builder.rb (hunk 4 above)
Comment (ndushay) [reply app/services/title_builder.rb]: good point; removing.

File: app/services/title_builder.rb (hunk 3 above)
Comment (ndushay) [reply app/services/title_builder.rb]: good point; removing.

File: app/services/title_builder.rb (hunk 2 above)
Comment (ndushay) [reply app/services/title_builder.rb:127]: just in case.  I've found that data is often dirty.

File: app/services/title_builder.rb (hunk 1 above)
Comment (ndushay) [reply app/services/title_builder.rb]: good idea; done.

**Review by ndushay — COMMENTED** [review]
thanks for the review;  i took nearly all your suggestions and the code is better for them.  Ready for re-reivew.

File: app/services/title_builder.rb (hunk 2 above)
Comment (aaron-collier) [reply app/services/title_builder.rb:127]: this looks like it could result in a "title_part_value, " (with comma blank at the end) if the structured value is nil. Is that ok?

Comment (ndushay) [reply app/services/title_builder.rb]: any trailing punct is going to be removed with remove_trailing_punctuation as the last line of the public build method

**Review by aaron-collier — APPROVED** [review]
