### PR TITLE
[HOLD] Refactor Indexer and handle not found in rolling indexer.

### LINKED ISSUE #842: Handle cocina object not found
## Backtrace

    line 57 of [PROJECT_ROOT]/app/services/indexer.rb: block in fetch_model_with_metadata
    line 55 of [PROJECT_ROOT]/app/services/indexer.rb: fetch_model_with_metadata
    line 16 of [PROJECT_ROOT]/app/services/indexer.rb: load_and_index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49898/faults/85373022)

### PR DESCRIPTION
**Pull request by justinlittman**
closes #842

## Why was this change made? 🤔
Cleaner code and better error messages.

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test) that exercise indexing*** (e.g. searches in Argo for newly created/updated items, access_indexing_spec) and/or test in [stage|qa] environment, in addition to specs. ⚡

QA integration tests

### CODE REVIEW

File: app/controllers/dor_controller.rb [hunk 1]
```diff
@@ -20,45 +15,33 @@ def reindex_from_cocina
     cocina_with_metadata = build_model_and_metadata(cocina_hash: cocina_hash,
                                                     created_at: params[:created_at].presence,
                                                     updated_at: params[:updated_at].presence)
-    druid = cocina_with_metadata.externalIdentifier
-    reindex_object(Success(cocina_with_metadata))
-    render status: :ok, plain: "Successfully updated index for #{druid}"
-  rescue CocinaModelBuildError => e
+    Indexer.reindex(solr: solr, cocina_with_metadata: cocina_with_metadata, commit_within: commit_within_param)
+    render status: :ok, plain: "Successfully updated index for #{cocina_with_metadata.externalIdentifier}"
+  rescue Cocina::Models::Error => e
```
Comment (justinlittman) [inline app/controllers/dor_controller.rb:20]: Just catching the actual errors instead of catching StandardError (below) and raising a custom error make this cleaner.

File: app/controllers/dor_controller.rb [hunk 2]
```diff
@@ -20,45 +15,33 @@ def reindex_from_cocina
...
-    render status: :unprocessable_entity, plain: "Error building Cocina model from json: '#{e.cause.message}'; cocina=#{cocina_hash.to_json}"
+    hb_context = { cocina: cocina_hash.deep_symbolize_keys, build_error: e.message } # calling #deep_symbolize_keys makes for a more readable hash
+    Honeybadger.notify('Error building Cocina model', context: hb_context, backtrace: e.backtrace)
+    render status: :unprocessable_entity, plain: "Error building Cocina model from json: '#{e.message}'; cocina=#{cocina_hash.to_json}"
   end
 
   def delete_from_index
-    solr.delete_by_id(params[:id], commitWithin: params.fetch(:commitWithin, 1000).to_i)
-    solr.commit unless params[:commitWithin]
+    Indexer.delete(solr: solr, identifier: params[:id], commit_within: commit_within_param)
```
Comment (justinlittman) [inline app/controllers/dor_controller.rb:28]: Added delete to Indexer to abstract from solr fu.

File: app/jobs/reindex_job.rb [hunk 3]
```diff
@@ -3,33 +3,25 @@
 # Reindexes an object
 class ReindexJob
   include Sneakers::Worker
-  include Dry::Monads[:result]
```
Comment (justinlittman) [inline app/jobs/reindex_job.rb:6]: Cleaner interface to Indexer means that consumers of the class don't need to muck with monads.

File: app/services/indexer.rb [hunk 4]
```diff
@@ -1,72 +1,68 @@
...
 
 class Indexer
-  include Dry::Monads[:result]
+  # @param [RSolr::Client] solr
+  # @param [String] identifier for cocina object
+  # @param [Integer] commit within milliseconds; if nil, then immediately committed.
+  # @raise [Dor::Services::Client::NotFoundResponse]
+  # @raise [Dor::Services::Client::UnexpectedResponse]
+  # @return [Hash,Nil] solr document or nil if indexing failed
+  def self.load_and_index(solr:, identifier:, commit_within: 1000)
```
Comment (justinlittman) [inline app/services/indexer.rb:10]: Notice that commit_within is an argument with a default of 1000. This obviates the need for consumers of this class to be passing around additional attributes that are really about setting the commit.

File: app/services/indexer.rb [hunk 5]
```diff
@@ -1,72 +1,66 @@
 # frozen_string_literal: true
 
 class Indexer
-  include Dry::Monads[:result]
```
Comment (justinlittman) [inline app/services/indexer.rb:4]: When you clean up this class, monads aren't really necessary.

File: app/services/indexer.rb [hunk 6]
```diff
@@ -1,72 +1,66 @@
...
+    reindex(cocina_with_metadata: cocina_with_metadata)
   end
 
   # Indexes the provided Cocina object to solr
-  # NOTE: this doesn't commit automatically
-  def reindex(add_attributes:, cocina_with_metadata:)
-    solr_doc = nil
-    logger.info 'document found, now generating document solr'
-    # benchmark how long it takes to convert the object to a Solr document
-    to_solr_stats = Benchmark.measure('to_solr') do
```
Comment (justinlittman) [inline app/services/indexer.rb:34]: At this point, benchmarking isn't necessary.

File: bin/rolling_index [hunk 7]
```diff
@@ -10,11 +10,14 @@ Daemons.run_proc('rolling index') do
...
     response['response']['docs'].each do |doc|
-      identifier = doc['id']
+      identifier = doc['id'].scrub('')
       ## Occasionally, we've seen invalid bytes in the identifier, so try to catch those:
       Honeybadger.notify("Identifier isn't valid utf-8", { identifier: identifier, bytes: identifier.unpack('C*') }) unless doc['id'].valid_encoding?
-      indexer = Indexer.new(solr: solr_conn, identifier: identifier.scrub(''))
-      indexer.load_and_index
+      begin
+        Indexer.load_and_index(solr: solr_conn, identifier: identifier)
+      rescue Dor::Services::Client::NotFoundResponse
```
Comment (justinlittman) [inline bin/rolling_index:18]: This is the change that cleans up the HB messages that prompted this work.

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: bin/rolling_index [hunk 8]
```diff
@@ -10,11 +10,16 @@ Daemons.run_proc('rolling index') do
...
+      # Occasionally, we've seen invalid bytes in the identifier, so try to catch those:
       Honeybadger.notify("Identifier isn't valid utf-8", { identifier: identifier, bytes: identifier.unpack('C*') }) unless doc['id'].valid_encoding?
-      indexer = Indexer.new(solr: solr_conn, identifier: identifier.scrub(''))
-      indexer.load_and_index
+      begin
+        Indexer.load_and_index(solr: solr_conn, identifier: identifier)
+      rescue Dor::Services::Client::NotFoundResponse
+        Honeybadger.notify('Rolling indexer cannot reindex since not found.', { druid: identifier })
+        # Clean up cruft in QA and stage
+        Indexer.delete(solr: solr_conn, identifier: identifier) unless Rails.env.production?
```
[the remark this answers is not in the document]
Comment (justinlittman) [reply bin/rolling_index:21]: Duh. And here I thought I was being clever.

**Review by ndushay — APPROVED** [review]
LGTM.

**Review by jcoyne — APPROVED** [review]
